### ISSUE TITLE
How to change the current index/time

### ISSUE THREAD

**Issue by ToniestTony** [dualB/Melody#4]
This isn't really an issue, I really like this library and I was wondering if there is a way to manually change the index/time of a music currently playing or in pause and if there isn't how to do it manually in the code? I am also using Musician, basically I want to play a music, pause it to play a sound, then keep playing the music on the same Musician variable (I only have a one speaker on my arduino).

**Comment by ToniestTony** [comment]
After trying some stuff, I actually found a solution for this, create 2 Musician instances, for example a music and a sound one and when one is playing, then stop refreshing the other one in the loop!

**Comment by dualB** [comment]
Thank you for your feedback, I'm glad that the library is useful for you!
If you think of any kind of improvement, let me know!

**Comment by dualB** [comment]
Je pense peut-être implémenter un "player" plus simple, qui permettrait de faire jouer la musique à l'aide de fonction callback. À suivre.
